# Site settings
title: João F. Corsini
email: jf.corsini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website to show a bit about myself from work experience to my
  in construction portfolio.
baseurl: ""
url: "http://jfcorsini.me"
twitter_username: jfcorsini
github_username:  jfcorsini

header_name: João F. Corsini
<<<<<<< HEAD
sub_header: Web Developer
=======
sub_header: Web developer
>>>>>>> f38ac329af1d249ac1fe6446ed8cbbc8c8de1b67
